🐛 Use different delimiter `fix 381e3f5`
sed: -e expression #1, char 38: unknown option to `s'
Error: Process completed with exit code 1.

To fix this issue, use a different delimiter that does not conflict with the text being replaced. For example, you can use the pipe symbol (`|`) as the delimiter instead.

Signed-off-by: Parixshit <87859520+Parixshit@users.noreply.github.com>